#!/bin/sh

[[ "$1" = unlink || "$1" = u ]] && readonly CMD=unlink && shift || readonly CMD=link

for i in _scripts/*; do
	[ $CMD = link ] && ln -s $i ./
	[ $CMD = unlink ] && unlink "$(basename "$i")"
done
