#!/bin/sh

check_deps() {
	for cmd in $@; do
		[ -z "$(command -v "$cmd")" ] && {
			>&2 echo "No such command '$cmd'"
			exit 1
		}
	done
}

set_args() {
	[ $# -eq 2 ] && {
		readonly FILE_MASK=$1
		shift
	} || readonly FILE_MASK="*.?pp"

	readonly REGEX_STR=$1 && shift
}


get_sources() {
	find . -type f -name "$FILE_MASK"
}

parallelize() {
	local readonly THREADS=$1
	shift

	awk \
"
	BEGIN {
		i = 0;
	} {
		if(++i == $THREADS) {
			i = 0;
			print \"wait\"
		}
		print \"$@ \"\$0\" &\"
	}
"
	# xargs -n 1 -P "$THREADS" $@
}


colorize() {
	trap '' INT

	local readonly FILE=$1
	shift

	pygmentize -f 256 -O style=native -g "$FILE" | nl

	trap 1 INT
}

process_source() {
	local readonly FILE=$1
	shift

	colorize "$FILE" \
		| grep -E "$REGEX_STR"
}

main() {
	set_args $@
	check_deps find xargs nl pygmentize grep awk

	export -f process_source
	get_sources "$FILE_MASK" | parallelize 25 process_source
}

main $@
