#!/bin/bash

[ -z "$LINUXDEPLOY_APPIMAGE" ] && {
  echo "error: LINUXDEPLOY_APPIMAGE is not defined"
  exit 1
}

mkdir build_appimage
cd build_appimage
cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
make install -j4 DESTDIR=AppDir
$LINUXDEPLOY_APPIMAGE --appdir AppDir -i AppDir/resources/snake.png -d AppDir/resources/snake.desktop -e AppDir/usr/snake --output appimage
